status/src/main.rs

What about this, @rnestler?
Solves #6.

Read port from env var

---

status/src/main.rs
status/src/utils.rs

Let's keep the main module clean and simple.

Moved get_port function to utils module

---

src/main.rs

Verify the JSON response.
I'm not sure if we can prettify the output somehow. If we use raw strings, then the leading whitespace is also kept.
@rnestler can you review please? :)

Added a test for the build_response_json function

---

src/main.rs

- ContentLength
- ContentType
- CacheControl
- AccessControlAllowOrigin
@rnestler can you review?

Set some HTTP headers

---

src/main.rs
src/spaceapi.rs

- Added `Optional` type
- Implemented `ToJson` for all SpaceAPI types
Fixes #15.
@rnestler can you review please? :)

Moved to ToJson based serialization

---

Cargo.toml

Rename the package and add some more fields. See http://doc.crates.io/manifest.html#package-metadata

update the cargo package metadata

---

.travis.yml

See http://docs.travis-ci.com/user/migrating-from-legacy/ for details.

Migrate to container based TravisCI testing

---

Cargo.toml
Makefile
README.rst
spaceapi/src/lib.rs
spaceapi_server/src/datastore.rs
spaceapi_server/src/lib.rs
src/main.rs

Timeslot at EuroPython without any interesting talks ;) So I improved the docs a bit.
Generate beautiful documentation with ``make docs``.

Improved documentation

---

Dockerfile
README.rst

This is based on PR #36, so please merge that one first.
This commit introduces a Dockerfile for easier deployment.
@schmijos @rnestler please review :)

Dockerfile

---

README.rst
spaceapi/src/lib.rs
spaceapi/src/sensors.rs
spaceapi/src/utils.rs
spaceapi_server/src/lib.rs
src/main.rs

FINALLY! This took me many hours and a few changes in the approach...
Sensors can now be registered on the server. They are being read when generating the output.
The sensor test is commented out, but I could already use some review from @rnestler @schmijos :)
When this PR is merged, I think we've reached the goals of #22, hoorray! :sparkles: :tada: :balloon:

Sensor registration

---

spaceapi/src/lib.rs
spaceapi_server/idee.txt
spaceapi_server/src/datastore/common.rs
spaceapi_server/src/datastore/mod.rs
spaceapi_server/src/datastore/redis_store.rs
spaceapi_server/src/lib.rs
spaceapi_server/src/sensors.rs
src/main.rs

I tried to make the public API of the two modules a bit nicer. For
this, I had to split up a few modules into submodules.

API cleanup

---

Cargo.toml
spaceapi/Cargo.toml
spaceapi/src/lib.rs
spaceapi/src/sensors.rs
spaceapi/src/utils.rs
spaceapi_server/src/lib.rs
spaceapi_server/src/sensors.rs
src/main.rs

Move SensorTemplate to Sensor conversion into SensorTemplate trait
@dbrgn Please take a look

Refactor sensor templates

---

src/main.rs

The only thing that's still missing compared to the current live
version is the opening state.

Added missing data to coredump_status output

---

spaceapi/src/utils.rs
spaceapi_server/src/lib.rs

This updates the open state according to the `value` in the people_now_present sensor. Note that currently it updates only the `open` field. Maybe we should also add a `StateTemplate` similar to the sensor templates. Or provide a hook or something similar to update the state variable.

Update open state

---

Makefile
README.rst
spaceapi/src/sensors.rs
spaceapi_server/Cargo.toml
spaceapi_server/src/lib.rs
spaceapi_server/src/sensors.rs

- What if a sensor has the wrong value?
- What if redis is down?
There should be proper error logging.

Handle connection failures

---

Cargo.toml
spaceapi/Cargo.toml
spaceapi_server/Cargo.toml
spaceapi_server/src/lib.rs

Does currently work with any path in the URL and does no checking
whatsoever.
try it out with http://127.0.0.1:3000/foobar?people_present=20
@dbrgn @schmijos please have a look at it

[RFC] server: First hack to update DataStore items

---

src/main.rs

Let's change this to the vorstand ML.

Updated contact email

---

spaceapi/src/sensors.rs
spaceapi/src/status.rs
spaceapi_server/src/server/handlers.rs
src/main.rs

The `state` object can contain a message. It could depend on the opening status.

Add a way to specify the state message

---

Dockerfile
README.md

We need this for the deployment.

Upgrade rust version in Dockerfile

---

AUTHORS.md
AUTHORS.rst
CONTRIBUTING.md

What do you think about this, @rnestler @schmijos @dns2utf8?
We could also use it for other projects.

Added CONTRIBUTING.md

---

spaceapi_server/src/server/handlers.rs

The println!() macro just prints to stdout. The log macros may output to
any output.

Use logging instead of println

---

src/main.rs

Add room temperature sensor

---

src/main.rs

Fixes #82
This will improve performance so much it will blow your mind! :sparkles: :stuck_out_tongue_winking_eye: :sparkles:

Replace to_string() with into() in main

---

src/main.rs

Fix cam URL

---

src/main.rs

the old File is still online, can we remove it?
https://webcam.coredump.ch/cams/ultimaker.jpg

Add new Paths for Webcams

---

Cargo.toml
src/main.rs

I would change the wording of the open status from
> Open every Monday from 20:00
to 
> Open every Monday from 20:00 (for members: 24/7)
or something similar.

Change Wording of Open Status

---

src/main.rs

Add third webcam

---

Cargo.lock
Cargo.toml
src/main.rs

It should still work the same as before ;)

Update to spaceapi-server 0.2

---

Dockerfile

Update compiler inside Dockerfile

Rust compiler

---

Cargo.toml
README.md
src/main.rs

This is what broke our server instance :)

Read Redis connection info from env vars

---

Cargo.lock
src/main.rs

Remove webcam[2]

---

src/main.rs

Update location data

---

src/main.rs

We can have two, one near the entrance and one in the back where the tables are :)

Add second temperature sensor

---

src/main.rs

Add ext_ccc field

---

.circleci/config.yml
.travis.yml
README.md

Fixes #119, fixes #110.
Replaces #112.

Set up CircleCI and Docker Hub

---

src/main.rs

- Update coordinates
- Rename sensors
- Remove "people in cyberspace" sensor
CC @rnestler

New location

---

src/main.rs

Channel is already registered. Project registration is pending.

Switch from freenode to libera.chat

---

src/main.rs

Our post-officer moved :slightly_smiling_face:

Update our postal address

---

src/main.rs

- Remove twitter
- Add mastodon
- Add phone
- Fix e-mail

Update contact details
