status/src/spaceapi.rs

Some points I noticed:
- The match is not necessary for a single possible type. Simply use the "dot" syntax.
- The return value of a closure can be derived automatically. `|enc| -> _ {` can be simplified to `|enc| {`.
- An explicit return is not necessary, simply leave an expression at the end of the scope.
- I'm not sure why `*p_url` was dereferenced, but `p_type` not. Apparently it's not necessary at all.
- Removed some redundant braces
Before:
```rust
match *self {
Feed { _type: ref p_type, url: ref p_url } =>
encoder.emit_struct("Feed", 2usize, |enc| -> _ {
try!(enc.emit_struct_field( "type", 0usize, |enc| p_type.encode(enc)));
return enc.emit_struct_field("url", 1usize, |enc| -> _ { (*p_url).encode(enc) });
}),
}
```
After:
```rust
encoder.emit_struct("Feed", 2usize, |enc| {
try!( …
```

Simplified Feed Encodable impl

---

spaceapi_server/src/datastore.rs

No need to redirect through a struct. The error type can be an enum.
What I still not like is that while the ``DataStore`` trait enables
out-of-crate implementations, one still has to edit the enum to be able to
return custom errors.
Maybe we should make ``DataStore`` (and all users of it) error type generic.
@dbrgn @schmijos

datastore: Clenup DataStoreError

---

spaceapi/src/lib.rs
spaceapi_server/src/lib.rs

- We previously didn't use the `Status` instance that was passed into the server. This is now fixed.
- `build_response_json` now returns `Json`, not `String`
- Improved tests
It's another step in the direction of fixing #22.
@rnestler can you review?

Server refactoring

---

.travis.yml
src/main.rs

It's probably a good thing if the spaceapi builds with the latest stable
toolchain, not only with beta / nightly.
Also I removed nightly because recently we hit a compiler bug: https://travis-ci.org/coredump-ch/spaceapi/builds/69862138, see https://github.com/rust-lang/rust/pull/26807 which fixed the error.
But maybe that's a good thing, so we uncover bugs in rustc.

travis: test with stable and beta, but not nightly

---

spaceapi_server/src/lib.rs

That way the URL is accessible to open in the browser from my terminal. :smiley:

server: Print full URL on serve()

---

README.rst

Running cargo run without ``--`` results in:
```
% cargo run  -i 0.0.0.0 -p 1337                                                                                                         :(
Unknown flag: '-i'
Usage:
cargo run [options] [--] [<args>...]
```

Readme: Fix cargo run command

---

Dockerfile
README.rst

Now it simply uses the default branch (in our case `rust`).

Fixed docker target branch and binary name

---

spaceapi_server/src/datastore/common.rs
spaceapi_server/src/datastore/hash_map_store.rs
spaceapi_server/src/datastore/mod.rs
spaceapi_server/src/datastore/redis_store.rs

So I implemented an alternative `DataStore` backend using a simple HashMap. This could be useful when writing unit tests since they are independent of any redis server and thus have no side effects.

Alternative datastore

---

spaceapi/src/lib.rs
spaceapi/src/optional.rs
spaceapi/src/sensors.rs
spaceapi/src/status.rs
spaceapi_server/src/lib.rs

The utils module contained only the Optional<T> struct. Also utils is a
very bad name for a module.

spaceapi: Rename utils module to optional

---

spaceapi_server/src/datastore/hash_map_store.rs
spaceapi_server/src/datastore/redis_store.rs

We had some warnings in the doc tests about unused return values:
```
src/datastore/redis_store.rs:52:9: 52:34 warning: unused result which must be used, #[warn(unused_must_use)] on by default
src/datastore/redis_store.rs:52         rs.store("key", "value");
^~~~~~~~~~~~~~~~~~~~~~~~~
```
By unwrapping them we fix the warnings and make sure that the unit test will fail.

server: Fix warnings in doc tests

---

spaceapi_server/src/datastore/common.rs
spaceapi_server/src/lib.rs
spaceapi_server/src/sensors.rs
src/main.rs

Apparently it's not needed to work correctly.

Remove Arc for SafeDataStore

---

Dockerfile
README.md
spaceapi_server/src/datastore/redis_store.rs

The Redis datastore should be configurable through env vars. This allows us to link a Docker container against a Redis container.

Redis config

---

Cargo.toml
Dockerfile
README.md

Repo was renamed from `spaceapi` to `status`.

Update repository URLs

---

README.md

Dockerhub should now be integrated with Github.

Changed docker image name

---

.gitignore
Cargo.lock
Dockerfile

- Start tracking `Cargo.lock`, this is a binary crate
- Update minimal Rust version in Docker
The missing `Cargo.lock` caused Docker to fail because the dependencies updated to versions that weren't compatible with 1.4.
@rnestler gave his verbal "OK" :)

Docker fix

---

src/main.rs

discourse.coredump.ch just seem to forward to coredump.ch

Fix link to coredump projects

---

Dockerfile

The latest build of the docker image failed: https://quay.io/repository/coredump/status?tab=info probably because the used Rust version is too old.

Update rust to 1.18.0 in Dockerfile

---

README.md
src/main.rs

Right now the opening status only considers the first entry in the people present sensor list, so only the physical presence is considered.
Is this good, or should we sum up all locations for the opening status? (Should Coredump be "open" even if nobody is there physically?)

Add people_in_cyberspace sensor endpoint

---

src/main.rs

We should list the postal address, not the location of the space.
Fixes #133.

Fix postal address

---

Cargo.toml

Readme.rst does not exist and cargo will use README.md by default if it
exists.

Remove wrong 'readme' metadata field
